const express = require('express')
const router = express.Router()
const userController = require("./controller")
const { isAdminOrStaff} = require('../../utils/checkRole')

router.post('/add',isAdminOrStaff, userController.createNewUser)
      .post('/update', userController.updateUser)
      .post('/delete',isAdminOrStaff, userController.deleteUserById)
      .post('/findByName', userController.findUserByName)
      .post('/findById', userController.findUserById)
      .get('/findAll', userController.getAllUser)
      .get('/findAllStaff', userController.findAllStaff)
      .get('/findAllTutorAndStudent', userController.findAllTutorAndStudent)
      .post('/findByRole', userController.findUsersByRole)
      .get('/findStudentsWithoutClass', userController.findStudentsWithoutClass)
      .get('/findStudentWithNoTutor', userController.findStudentWithNoTutor)
      .get('/findStudentsWithNoInteractionInSevenDays', userController.findStudentsWithNoInteractionInSevenDays)
      .post('/findMeetingsAndFilesByUserId', userController.findMeetingsAndFilesByUserId)
      .post('/findMessagesOfPeersByUserId', userController.findMessagesOfPeersByUserId)
      .get('/findMeetingsByTutorId', userController.findMeetingsByTutorId)
      .get('/findStudentsByTutorId', userController.findStudentsByTutorId)
      .get('/getStudentsAndStaffs', userController.getStudentsAndStaffs)
      .post('/findMessagesByUserId', userController.findMessagesByUserId)

module.exports = router